# Generated by Django 5.2.7 on 2025-11-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='loft.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('quantity', models.IntegerField(default=10, verbose_name='Количество')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('color_name', models.CharField(default='Белый', max_length=100, verbose_name='Название цвета')),
                ('color_code', models.CharField(default='#ffffff', max_length=20, verbose_name='Код цвета')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('length', models.IntegerField(verbose_name='Глубина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка на товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loft.category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_products', to='loft.modelproduct', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loft.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
