# Generated by Django 5.2.1 on 2025-12-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0006_order_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('text', models.CharField(max_length=350, verbose_name='Запрос клиента')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Запрос клиента',
                'verbose_name_plural': 'Запросы клиентов',
            },
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loft.order', verbose_name='Заказ'),
        ),
    ]
